### ISSUE TITLE
When I add a glb file in a collection, the 3D object does not render in the frontend. 

### ISSUE THREAD

**Issue by marknovelero-ideum** [br41nslug/directus-extension-3d-viewer#1]
When I add a .glb file to a collection, the 3D object does not render on the frontend. Thanks for creating this. I would really appreciate your help.

**Comment by m0ose** [comment]
I get an error in the terminal
 ```model-viewer.js:33559 
       GET http://localhost:8055/assets/810d13f3-26d2-41f4-aa68-0efefb550c06?access_token=null 401 (Unauthorized)
```
       
It seems like the `access_token=null` part is the problem because when I remove that from the url it downloads the file.

**Comment by br41nslug** [comment]
Thanks for reporting this! Since Directus version 10.10.0 which introduced the ["session cookie"](https://docs.directus.io/releases/breaking-changes.html#session-cookie-based-authentication), the `?access_token=` logic is no longer required.

**Comment by br41nslug** [comment]
resolved in https://github.com/br41nslug/directus-extension-3d-viewer/pull/3
